### ISSUE TITLE
"stuck" pins on cluster

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1319]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: v0.13.x
 - Installation method: dist.ipfs.io

**Describe the bug:**

I have a cluster with fairly frequent rotating pins, which I "cleaned" up. I currently only have 3 pins on it:

```
$ ipfs-cluster-ctl pin ls
bafkreiaasrrzdg7qcqqsphd37n7zhwq5uigmaobmyufzzgx2uvpjyjt2de | lowpower.json@d557f23 | PIN | Repl. Factor: -1 | Allocations: [everywhere] | Recursive | Metadata: no | Exp: ∞
bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le | service.json@d557f23 | PIN | Repl. Factor: -1 | Allocations: [everywhere] | Recursive | Metadata: no | Exp: ∞
bafybeibyfotqds5azsdskdi4gyc2pjsl4xsnb3ibyb4p7b3dphwixcyfii | x86-64.archlinux.pkg.pacman.store | PIN | Repl. Factor: -1 | Allocations: [everywhere] | Recursive | Metadata: no | Exp: ∞
```

But `ipfs-cluster-ctl status` still shows a lot of older pins floating around on the nodes. Why? 

```
$ ipfs-cluster-ctl status
bafybeifd6ypozbmgekxkectkatxjo4sra67dpmm7x6yqlwt7faw72vnsi4 | x86-64.archlinux.pkg.pacman.store@2021-02-23T14:35:35+00:00:
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.925954072Z
bafybeiacewhwg3vyl2vuizhetgzgeztggtpl6cetd7fcokb3lew2og66qm | x86-64.archlinux.pkg.pacman.store@2021-02-23T14:32:24+00:00:
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.92790768Z
bafybeiaqukfigtrrca3tvp7mickvkcbmrme4gd5ht5alwxikgbdj7kuw3i | x86-64.archlinux.pkg.pacman.store@2021-02-04T16:49:43+00:00:
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.929733209Z
bafybeiai2lhrnb6v53jkt7wf5wd7uljaoko342x3oxswe3lqkmxuws45ei | x86-64.archlinux.pkg.pacman.store@2020-12-23T21:10:40+00:00:
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.928491327Z
    > vidar.pacman.store   : PINNED | 2021-03-07T17:59:40.202831046Z
    > home-ws              : PINNED | 2021-03-07T17:59:38.260687143Z
    > b                    : PINNED | 2021-03-07T17:59:40.936168253Z
bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly | x86-64.archlinux.pkg.pacman.store@2021-02-24T01:01:37+00:00:
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.929150547Z
    > vidar.pacman.store   : PINNED | 2021-03-07T17:59:40.206110285Z
    > home-ws              : PINNED | 2021-03-07T17:59:38.261169084Z
    > b                    : PINNED | 2021-03-07T17:59:40.936983826Z
bafybeidyjzeoez3kmzmmprvsc7gdlui4b6uavvbqgo7oquyesfym2tmdne:
    > home-ws              : PINNING | 2021-03-07T17:05:28.995248934Z
bafybeidzzndae6b2cx4mqelcqiyxsmjzkxzlbmnymtaep3o3bfvot7d76m:
    > home-ws              : PIN_QUEUED | 2021-03-07T17:05:28.995204301Z
bafkreiaasrrzdg7qcqqsphd37n7zhwq5uigmaobmyufzzgx2uvpjyjt2de | lowpower.json@d557f23:
    > odin.pacman.store    : PINNED | 2021-03-07T18:59:30.373160826+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.926693609Z
    > vidar.pacman.store   : PINNED | 2021-03-07T17:59:40.199972079Z
    > home-ws              : PINNED | 2021-03-07T17:59:38.261982304Z
    > b                    : PINNED | 2021-03-07T17:59:40.934599944Z
bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le | service.json@d557f23:
    > odin.pacman.store    : PINNED | 2021-03-07T18:59:30.376286049+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.927351532Z
    > vidar.pacman.store   : PINNED | 2021-03-07T17:59:40.201589733Z
    > home-ws              : PINNED | 2021-03-07T17:59:38.262378464Z
    > b                    : PINNED | 2021-03-07T17:59:40.935387264Z
bafybeibyfotqds5azsdskdi4gyc2pjsl4xsnb3ibyb4p7b3dphwixcyfii | x86-64.archlinux.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2021-03-07T18:59:30.378988918+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-07T17:59:40.930326038Z
    > vidar.pacman.store   : PINNED | 2021-03-07T17:59:40.207356673Z
    > home-ws              : PINNED | 2021-03-07T17:59:38.261625717Z
    > b                    : PINNED | 2021-03-07T17:59:40.933629556Z

```

**Comment by hsanjuan** [comment]
I would usually mean that state has diverged in those peers. This may be caused by an issue that was fixed in 0.13.1 only. Other cause could be wrongly setup trusted_peers.

**Comment by RubenKelevra** [comment]
There's only one trusted peer (running) and I'm sure that they use my service file.

It might have something to do with the timeout feature. I used to add pins with a timeout of 2 days.

Maybe they were just lagging behind and were still in the pinning or pin_queued status while the timeout has run out?

---

Anyway, I tried to fix this status from my side, and added those cids again to the cluster-pinset and removed them again. This resulted in this status:

```
$ ipfs-cluster-ctl status
bafybeigydmdej2ucxaiqu6sqvp5vrj432m2vt5yxxtl6b4v2k7klacr3cq | x86-64.archlinux.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2021-03-12T21:37:57.493332931+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-12T20:38:18.479563096Z
    > b                    : PINNED | 2021-03-12T20:38:19.667066603Z
bafybeiacewhwg3vyl2vuizhetgzgeztggtpl6cetd7fcokb3lew2og66qm:
    > nas1.polaris.lan     : PIN_ERROR: the item should be pinned but it is not | 2021-03-12T20:38:18.480099154Z
bafybeiai2lhrnb6v53jkt7wf5wd7uljaoko342x3oxswe3lqkmxuws45ei:
    > nas1.polaris.lan     : PIN_ERROR: the item should be pinned but it is not | 2021-03-12T20:38:18.48010102Z
    > b                    : PIN_ERROR: the item should be pinned but it is not | 2021-03-12T20:38:19.668389279Z
bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly:
    > nas1.polaris.lan     : PIN_ERROR: the item should be pinned but it is not | 2021-03-12T20:38:18.48010242Z
    > b                    : PIN_ERROR: the item should be pinned but it is not | 2021-03-12T20:38:19.668391191Z
bafybeiaqukfigtrrca3tvp7mickvkcbmrme4gd5ht5alwxikgbdj7kuw3i:
    > nas1.polaris.lan     : PIN_ERROR: the item should be pinned but it is not | 2021-03-12T20:38:18.480103515Z
bafybeifd6ypozbmgekxkectkatxjo4sra67dpmm7x6yqlwt7faw72vnsi4:
    > nas1.polaris.lan     : PIN_ERROR: the item should be pinned but it is not | 2021-03-12T20:38:18.480104687Z
bafkreiaasrrzdg7qcqqsphd37n7zhwq5uigmaobmyufzzgx2uvpjyjt2de | lowpower.json@d557f23:
    > odin.pacman.store    : PINNED | 2021-03-12T21:37:57.493346436+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-12T20:38:18.480005966Z
    > b                    : PINNED | 2021-03-12T20:38:19.668340331Z
bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le | service.json@d557f23:
    > odin.pacman.store    : PINNED | 2021-03-12T21:37:57.493330636+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-12T20:38:18.479405132Z
    > b                    : PINNED | 2021-03-12T20:38:19.667411038Z
```

(there should be only 3 pins on the cluster)

When I run `ipfs-cluster-ctl recover` they get readded as pin_queued and the nodes seem to start to analyze those pins, but I still cannot remove them, since they are no longer part of the pinset.

Weird.

Hope this got fixed in 0.13.1 (don't know which version they run).

**Comment by hsanjuan** [comment]
Tbh, looks like a bug.

**Comment by hsanjuan** [comment]
It may not be a consensus-layer bug, perhaps it is the pin tracker and I will start looking there.

**Comment by hsanjuan** [comment]
`ipfs-cluster-ctl --enc=json peers ls` should show version information.

@RubenKelevra , what happens when you `ipfs-cluster-ctl status <cid>` for some of the CIDs that were unpinned ? Do they show the same status as with the full list?

**Comment by hsanjuan** [comment]
I've done some checking. If the nodes showing wrong status are under 0.13.1, then I would put my money on the issue that was fixed here: https://github.com/ipfs/ipfs-cluster/pull/1288 . Otherwise, there might be a problem in go-ds-crdt, but the datastore test suite is quite extense and I think it is unlikely there is an issue there that would cause this behaviour. The pintracker code seems mostly fine too.

**Comment by RubenKelevra** [comment]
Okay, just for reference, this is how the pinset looks like right now:

<details>

```
$ ipfs-cluster-ctl status
bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le | service.json@d557f23:
    > odin.pacman.store    : PINNED | 2021-03-15T18:28:26.623054422+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.2249653Z
    > vidar.pacman.store   : PINNED | 2021-03-15T17:28:51.553808127Z
    > home-ws              : PINNED | 2021-03-15T17:28:50.658027607Z
    > b                    : PINNED | 2021-03-15T17:28:53.919095214Z
bafybeigrbxon5zjndqtgldf6y3fhz7twbhbfchubpo2dejh7n3gzzwostq | x86-64.archlinux.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2021-03-15T18:28:26.623055003+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.223647433Z
    > vidar.pacman.store   : PINNED | 2021-03-15T17:28:51.553497482Z
    > home-ws              : PINNED | 2021-03-15T17:28:50.658020664Z
    > b                    : PINNED | 2021-03-15T17:28:53.918869598Z
bafybeiacewhwg3vyl2vuizhetgzgeztggtpl6cetd7fcokb3lew2og66qm:
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.225046342Z
bafybeiai2lhrnb6v53jkt7wf5wd7uljaoko342x3oxswe3lqkmxuws45ei:
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.222775325Z
    > vidar.pacman.store   : PIN_QUEUED | 2021-03-14T05:47:53.786631246Z
    > home-ws              : PINNING | 2021-03-14T08:56:16.319692317Z
    > b                    : PINNED | 2021-03-15T17:28:53.920240673Z
bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly:
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.224889821Z
    > vidar.pacman.store   : PINNING | 2021-03-15T02:28:31.94244722Z
    > home-ws              : PIN_QUEUED | 2021-03-14T08:56:16.319659115Z
    > b                    : PINNED | 2021-03-15T17:28:53.918653465Z
bafybeiaqukfigtrrca3tvp7mickvkcbmrme4gd5ht5alwxikgbdj7kuw3i:
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.222752781Z
bafybeifd6ypozbmgekxkectkatxjo4sra67dpmm7x6yqlwt7faw72vnsi4:
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.225499019Z
bafkreiaasrrzdg7qcqqsphd37n7zhwq5uigmaobmyufzzgx2uvpjyjt2de | lowpower.json@d557f23:
    > odin.pacman.store    : PINNED | 2021-03-15T18:28:26.623053831+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:28:53.224868731Z
    > vidar.pacman.store   : PINNED | 2021-03-15T17:28:51.55559925Z
    > home-ws              : PINNED | 2021-03-15T17:28:50.658027126Z
    > b                    : PINNED | 2021-03-15T17:28:53.919032663Z
```

</details>

_Only the named pins should be there. The others lost their names as I removed them and they got readded somehow by the nodes._

@hsanjuan wrote:
> `ipfs-cluster-ctl --enc=json peers ls` should show version information.

Looks like 0.13.1 didn't fix it. Furthermore, `vidar.pacman.store` is affected, on which I cleaned off the cluster-state files, and launched the cluster-follower from a fresh start.

0.13.0 nodes:
- `home-ws`
- `nas1.polaris.lan`

0.13.1 nodes:
- `b`
- `vidar.pacman.store`
- `odin.pacman.store` (the trusted node)

@hsanjuan wrote:
> what happens when you `ipfs-cluster-ctl status <cid>` for some of the CIDs that were unpinned ? Do they show the same status as with the full list?

Well, the cluster status for bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le is wrong as well (just noticed). The full list shows it pinned everywhere, while the status with the CID shows it just pinned on `odin.pacman.store`. **Strangely also the nodes-ids won't be resolved ... while this pin is set to -1/-1 it might be pinned long enough to have seen all nodes disappear in this list, and the new ones are either not tracked properly or never started pinning?** All IDs listed below can only be found in the `cluster_peers` and `cluster_peers_addresses` arrays on various clients, from a long `peer ls`, but are not current clients.

```
$ ipfs-cluster-ctl status bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le
bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le | service.json@d557f23:
    > odin.pacman.store    : PINNED | 2021-03-15T18:39:24.68273316+01:00
    > 12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth : REMOTE | 2021-03-15T18:39:24.682064296+01:00
      > 12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA : REMOTE | 2021-03-15T18:39:24.682064296+01:00
    > 12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR : REMOTE | 2021-03-15T18:39:24.682064296+01:00
    > 12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA : REMOTE | 2021-03-15T18:39:24.682064296+01:00
```

This is the most recent pin on the cluster, which looks as it should:

```
$ ipfs-cluster-ctl status bafybeigrbxon5zjndqtgldf6y3fhz7twbhbfchubpo2dejh7n3gzzwostq
bafybeigrbxon5zjndqtgldf6y3fhz7twbhbfchubpo2dejh7n3gzzwostq | x86-64.archlinux.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2021-03-15T18:39:40.830451814+01:00
    > nas1.polaris.lan     : PINNED | 2021-03-15T17:40:06.5346169Z
    > vidar.pacman.store   : PINNED | 2021-03-15T17:40:07.000415113Z
    > home-ws              : PINNED | 2021-03-15T17:40:06.494757457Z
    > b                    : PINNED | 2021-03-15T17:40:06.472267662Z
```

Here's a "stuck" pin:

```
$ ipfs-cluster-ctl status bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly
bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly:
    > 12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx : UNPINNED | 2021-03-15T18:48:25.588028951+01:00
    > 12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth : UNPINNED | 2021-03-15T18:48:25.588028951+01:00
    > 12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA : UNPINNED | 2021-03-15T18:48:25.588028951+01:00
    > 12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR : UNPINNED | 2021-03-15T18:48:25.588028951+01:00
    > 12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA : UNPINNED | 2021-03-15T18:48:25.588028951+01:00
```

Hope this helps!

**Comment by hsanjuan** [comment]
> Looks like 0.13.1 didn't fix it.

Problem is, if there is a single 0.13.0 node in the cluster, they may be blocking pubsub message propagation even if the other peers are 0.13.1. Depends how the pubsub graph is formed.

Anyways, I'm not sure it is that. @RubenKelevra can you send me the following jsons?

```
ipfs-cluster-ctl --enc=json pin ls
ipfs-cluster-ctl --enc=json status
ipfs-cluster-ctl --enc=json status bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le
```

Or would it be possible for me to join this cluster?

**Comment by RubenKelevra** [comment]
> > Looks like 0.13.1 didn't fix it.
> 
> Problem is, if there is a single 0.13.0 node in the cluster, they may be blocking pubsub message propagation even if the other peers are 0.13.1. Depends how the pubsub graph is formed.

Ah this makes sense! 

Masbe for future bugs it might be beneficial to have a "minimal required version" for cluster nodes, to just show the administrators of those node an error message and disconnect the nodes until they are updated. 

> Anyways, I'm not sure it is that. @RubenKelevra can you send me the following jsons?
> 
> ```
> ipfs-cluster-ctl --enc=json pin ls
> ipfs-cluster-ctl --enc=json status
> ipfs-cluster-ctl --enc=json status bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le
> ```
>
> Or would it be possible for me to join this cluster?

I think joining is easier, it's the http://pacman.store cluster :)

**Comment by RubenKelevra** [comment]
For completeness, here are the outputs you requested:

> `ipfs-cluster-ctl --enc=json pin ls`

<details>

```
[
    {
        "replication_factor_min": -1,
        "replication_factor_max": -1,
        "name": "lowpower.json@d557f23",
        "mode": "recursive",
        "shard_size": 104857600,
        "user_allocations": null,
        "expire_at": "0001-01-01T00:00:00Z",
        "metadata": null,
        "pin_update": null,
        "cid": {
            "/": "bafkreiaasrrzdg7qcqqsphd37n7zhwq5uigmaobmyufzzgx2uvpjyjt2de"
        },
        "type": 2,
        "allocations": [
            "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx"
        ],
        "max_depth": -1,
        "reference": null
    },
    {
        "replication_factor_min": -1,
        "replication_factor_max": -1,
        "name": "service.json@d557f23",
        "mode": "recursive",
        "shard_size": 104857600,
        "user_allocations": null,
        "expire_at": "0001-01-01T00:00:00Z",
        "metadata": null,
        "pin_update": null,
        "cid": {
            "/": "bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le"
        },
        "type": 2,
        "allocations": [
            "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx"
        ],
        "max_depth": -1,
        "reference": null
    },
    {
        "replication_factor_min": -1,
        "replication_factor_max": -1,
        "name": "x86-64.archlinux.pkg.pacman.store",
        "mode": "recursive",
        "shard_size": 0,
        "user_allocations": null,
        "expire_at": "0001-01-01T00:00:00Z",
        "metadata": null,
        "pin_update": {
            "/": "bafybeihssscfdcp7kpsvhcvtgqgn4pnyxvd4euwt2cpqt2xf6r43lkara4"
        },
        "cid": {
            "/": "bafybeiawo2mqflgsxni3n4hqui2ve6tdk635fzofhgpjcq3nqhw73jhjuu"
        },
        "type": 2,
        "allocations": [],
        "max_depth": -1,
        "reference": null
    }
]
```

</details>

> `ipfs-cluster-ctl --enc=json status`


<details>

```
[
    {
        "cid": {
            "/": "bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le"
        },
        "name": "service.json@d557f23",
        "peer_map": {
            "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx": {
                "peername": "odin.pacman.store",
                "status": "pinned",
                "timestamp": "2021-03-16T10:49:02.295117535+01:00",
                "error": ""
            },
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.09545874Z",
                "error": ""
            },
            "12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA": {
                "peername": "vidar.pacman.store",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:48.690463343Z",
                "error": ""
            },
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:48.598311415Z",
                "error": ""
            },
            "12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA": {
                "peername": "b",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.832551686Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiddjp6xssoxkne6d73u5adwc2ofesdaxunntighdwb6h36nbncxrq"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.992590573Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeigba46kmmuqqi7kcvlvh46gnk5mu7queti3iquagbi4yyxpof3iui"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:31:49.23276327Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiah2ndpb3mvxgwj2kbm74ab6odz7tk6i56sfk2xsrxaekcp4iy3ze"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:58:09.205916611Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifjv2wjuyailatnc363kzub34eh76iztm6w6t4nlg7hp7ltwqbusy"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.345020826Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly"
        },
        "name": "",
        "peer_map": {
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.097350587Z",
                "error": ""
            },
            "12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA": {
                "peername": "vidar.pacman.store",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:48.696460951Z",
                "error": ""
            },
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "pin_queued",
                "timestamp": "2021-03-14T08:56:16.319659115Z",
                "error": ""
            },
            "12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA": {
                "peername": "b",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.832228281Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeidmwjhzvctvhi7lge7xj7cfeu6weort7bjr2mv7g7ev63xmfgzzpe"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:31:49.034108098Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeid52zuvuxwxb6gobevj5623txse4iiq4pduwf77rwcrdqioxcurle"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.411286728Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifa6a2rvgda63buqckzqcotp3cbeqoqiy7ocugb6qs7vgojwqxu4m"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:07.989958347Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeif5oxyxhvaip4qmmpos3dlilufdughefmlqd3rnvc2mkgnragztge"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.477962796Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiavuuus36ttiif4xtodrrlgqvtfi354jeyot4ufuouyi6rgfusz74"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:10.086131247Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeic3apoed7oytqaa7h2ags264jw7norwgb6q52qhsouvynahbnqjxm"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:10.247262498Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeig5kh7rdzrqfl5ggu4yj4zzhitg6mnarlww26bdmhiyl6tn24cblm"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.10235901Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifgp4vktspfl4jf3cfzcf4vd2hlommmx4o6mdwrwoem6eyisczwmi"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:07.657613904Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiaqukfigtrrca3tvp7mickvkcbmrme4gd5ht5alwxikgbdj7kuw3i"
        },
        "name": "",
        "peer_map": {
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.095209252Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiacewhwg3vyl2vuizhetgzgeztggtpl6cetd7fcokb3lew2og66qm"
        },
        "name": "",
        "peer_map": {
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.096875255Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeie37pk2bxi33e5w576tmxrcej4pnxgkjresp2jasms7kadeomw7su"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.174843584Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeihpu7nkw6fjz24yawuxa5ofot347grgmf4mold5ir4wkbw5kqa4be"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:31:49.298436364Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifdw4srjl4xu4tpm6c2h3m3wwufqxpxx3nphbay6r5oj4y3uegdjq"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:31:49.166493941Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiadkft3kejhiqp7vxm6eyz2xjoocxisvnqyzby5f2es2r4w775ruy"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.926023519Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeigzinbc4r7xdwdzhztgrdu4eajmrjk4uq2dvwbjcegzwg3fhdcafm"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpinning",
                "timestamp": "2021-03-16T09:47:40.636127906Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiawo2mqflgsxni3n4hqui2ve6tdk635fzofhgpjcq3nqhw73jhjuu"
        },
        "name": "",
        "peer_map": {
            "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx": {
                "peername": "odin.pacman.store",
                "status": "pinning",
                "timestamp": "2021-03-16T10:45:53.266749663+01:00",
                "error": ""
            },
            "12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA": {
                "peername": "vidar.pacman.store",
                "status": "pin_queued",
                "timestamp": "2021-03-16T09:46:24.204497831Z",
                "error": ""
            },
            "12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA": {
                "peername": "b",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.831014243Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiffvae4bb7xpq3rpayvvgwmk5pptpuz62ahtdsgbgy4ccoion6axi"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.196279591Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifaz3ejmtq6gio4hntzrtgmo64kwej5pjamnvnicfibfbkkvht3ym"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:31:49.100208362Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeidh6v6s6ujlobrrxp74oq2xdvu3rvouvyeqvl2iehgcgrfrsfzbne"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:58:09.072137422Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeicctm33s237zr64rnfcuxwefa5xyvcbjuvmqbbc7p2w5llle7r634"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:29:40.551759196Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiewon2p3cge6upkni3jauvo7z32brsfs7ofbgorwdgeiom5y2fcqq"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.554114696Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeibqskjvlxz3basi6on7mtnyjeew3cnm75f2psbrsjcep32ds26yda"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.678347726Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeibkikjcjr3knvsdb56rsadudnkdjxuaeke7j67t4vdmknzlwksghu"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.630212772Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeif2kb3pu75eqn3elmi4ky2zhjiavjejo7e5mdcey4w2tj5s6l3aiq"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T09:29:40.587160077Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifv7en4nt3ancv2ymxpgj6lpnqyyu6kv4yjvlqgx54oodwceomeba"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:07.723527737Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeigdpfyxwy66yhc2fe7dhgbkirtugb3s6kz4gpqve5sknaovu7ej2a"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:07.923217828Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeias27d37ighmn34s5fd7a77pfg4aaa5ui3u3lsqji6eaygcrslfnq"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.697505693Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeig2mtx4h7i2zsrjopznc3wvmsgi44mpwdcl2rlliofe5e5aszdvym"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:58:08.950872127Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeihdtelgypwtda7linzpw3jueguuoltxp6nv6xawyh73auhnurlbkq"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:58:09.139859451Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeihxe7sxkuipbxv3s6bl7l3y3neayfwxangeynote5wb3rcqzw5jhu"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.831293893Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiftk3fmhhculzguzxxdi7f74jrwgasibcj2ol3b4j7irfqz4zdtye"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.033352047Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeienmhrpnt5ndlbqe7qhtadskb26s6gbhjrp2rz4j4pz4ailo554wa"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "pin_queued",
                "timestamp": "2021-03-16T08:58:09.011498898Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeidh6c72gcjw6h2qjcons262ooj2y6schlwkgomayiuepdhy7tukpi"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.33729932Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiefk4xfivvoxlglcs2di4k3zddy46y4jkskqrjdwhe2x765whv7qe"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.611625622Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeigbyavdo4ddef6clwysthsjqpcozsnrvumiqp6hxjrefx7efrs2qu"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.865547084Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeihssscfdcp7kpsvhcvtgqgn4pnyxvd4euwt2cpqt2xf6r43lkara4"
        },
        "name": "x86-64.archlinux.pkg.pacman.store",
        "peer_map": {
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.097698881Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeih6quwb5cqrxtmlp7ymyhnqnblnlqfklg6adq734lp2jefxuwanpa"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:53:40.547497736Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeigrbxon5zjndqtgldf6y3fhz7twbhbfchubpo2dejh7n3gzzwostq"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:53:40.599622121Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeich63eu7hk2ebnggb3vqkgkp2b2qjndv2w7bzoqjlihyypxos7l34"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.269496156Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeidnutymaa23vxjlsepytgq5f6owqqeysgsyb5go3yk7mjj5ncufvm"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.128319804Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeidyghbznxuamx5cawu4tzl5regu7l22eyb7h6zhadqb6pexzvda7e"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.764367377Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiai2lhrnb6v53jkt7wf5wd7uljaoko342x3oxswe3lqkmxuws45ei"
        },
        "name": "",
        "peer_map": {
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.096007468Z",
                "error": ""
            },
            "12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA": {
                "peername": "vidar.pacman.store",
                "status": "pinning",
                "timestamp": "2021-03-16T01:08:40.949041421Z",
                "error": ""
            },
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "pinning",
                "timestamp": "2021-03-14T08:56:16.319692317Z",
                "error": ""
            },
            "12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA": {
                "peername": "b",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.833053353Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeify3edtegtwkchzoqshhmenfexyveo4scg2dnwv5jdzwatrxfowqa"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:07.790011585Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifd6ypozbmgekxkectkatxjo4sra67dpmm7x6yqlwt7faw72vnsi4"
        },
        "name": "",
        "peer_map": {
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.097610971Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifahnrf7rzax3cmhzcsaenfxi7jl5op2fi6c3ph7iiw4b7y7nkc6m"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.545057937Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeic3bjfflrva55ztucqjtw5pq76usvc4lsjryqsfnodvers2budo4e"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T08:31:48.913186618Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeidbm4zjidersornl2u5npbw3itzynunj74vzmj4m6kqobius24ykm"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.771862712Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeianzvspnvpe7h3d3slt5yvbrvjamx7fueqypxxhcyvi7dwgm72d5a"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.060553338Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeicmshz7knyrpx6e3hoy46q4j5kjccar5ezwmqjdcmkjqr22fa7bfa"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:08.932636634Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafkreiaasrrzdg7qcqqsphd37n7zhwq5uigmaobmyufzzgx2uvpjyjt2de"
        },
        "name": "lowpower.json@d557f23",
        "peer_map": {
            "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx": {
                "peername": "odin.pacman.store",
                "status": "pinned",
                "timestamp": "2021-03-16T10:49:02.295116313+01:00",
                "error": ""
            },
            "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
                "peername": "nas1.polaris.lan",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.097322046Z",
                "error": ""
            },
            "12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA": {
                "peername": "vidar.pacman.store",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:48.693102385Z",
                "error": ""
            },
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:48.598309852Z",
                "error": ""
            },
            "12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA": {
                "peername": "b",
                "status": "pinned",
                "timestamp": "2021-03-16T09:48:51.832262813Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiaew3p47gvf2na5zzhdk4i3zvkevrdzggnmbdc3zdznv5gazsagu4"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:07.85627407Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeigortrdjxd3k66jvazi6rhoz2pwftv6twjmvidiicp47nexs3spl4"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_error",
                "timestamp": "2021-03-16T09:47:40.636109292Z",
                "error": "Post \"http://127.0.0.1:5001/api/v0/pin/rm?arg=bafybeigortrdjxd3k66jvazi6rhoz2pwftv6twjmvidiicp47nexs3spl4\": context deadline exceeded"
            }
        }
    },
    {
        "cid": {
            "/": "bafybeifpixsrexmklslfocsfyl2aam5p36kbuvbzffwu42fcocnn5rzww4"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:10.152822453Z",
                "error": ""
            }
        }
    },
    {
        "cid": {
            "/": "bafybeiemg5nzkval3ppszvvclvwnfzcm2xtkra5j5i7u4w4f6xed4ek4pu"
        },
        "name": "",
        "peer_map": {
            "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
                "peername": "home-ws",
                "status": "unpin_queued",
                "timestamp": "2021-03-16T07:24:09.431075263Z",
                "error": ""
            }
        }
    }
]
```

</details>

> `ipfs-cluster-ctl --enc=json status bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le`

<details>

```
{
    "cid": {
        "/": "bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le"
    },
    "name": "service.json@d557f23",
    "peer_map": {
        "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx": {
            "peername": "odin.pacman.store",
            "status": "pinned",
            "timestamp": "2021-03-16T10:48:38.288962833+01:00",
            "error": ""
        },
        "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth": {
            "peername": "12D3KooWEweUswc6ZrQJACgGf13gmVBVVssK6LjCMENs6pu5yHth",
            "status": "remote",
            "timestamp": "2021-03-16T10:48:38.267337392+01:00",
            "error": ""
        },
        "12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA": {
            "peername": "12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA",
            "status": "remote",
            "timestamp": "2021-03-16T10:48:38.267337392+01:00",
            "error": ""
        },
        "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR": {
            "peername": "12D3KooWJpw6U8uuTa51GTYk8GTfFgszAWZvRKwXHG7Ubfwr5mRR",
            "status": "remote",
            "timestamp": "2021-03-16T10:48:38.267337392+01:00",
            "error": ""
        },
        "12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA": {
            "peername": "12D3KooWM2WefGdNzYLkduTBsTMrgtJevP3Wa8HV4tQ9pGfRTVXA",
            "status": "remote",
            "timestamp": "2021-03-16T10:48:38.267337392+01:00",
            "error": ""
        }
    }
}
```

</details>

**Comment by hsanjuan** [comment]
So one problem is that we have at least a pin with replication-factor -1 and 1 allocation defined:

```
    {
        "replication_factor_min": -1,
        "replication_factor_max": -1,
        "name": "service.json@d557f23",
        "mode": "recursive",
        "shard_size": 104857600,
        "user_allocations": null,
        "expire_at": "0001-01-01T00:00:00Z",
        "metadata": null,
        "pin_update": null,
        "cid": {
            "/": "bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le"
        },
        "type": 2,
        "allocations": [
            "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx"
        ],
        "max_depth": -1,
        "reference": null
    },
```

That should not be possible so it is a bug somewhere. If replication factor is -1 there should not be allocations set. This is confusing the code in several places. I think the rest of behaviors I can blame them on unsynced state perhaps due to the 0.13.0 issue, but let's fix this one first and check again.

**Comment by hsanjuan** [comment]
#1331 should fix that calling `status <cid>` on something that is pins shows stuff as REMOTE.

The case when `status <cid>` for something that is locally "not pinned" (per `pin ls`) shows as UNPINNED is intended behavior (because the state says it is not pinned, broadcast requests for status on other peers are not made and result is set as UNPINNED). I have to think if we want this, might remove it.

The case where something appears in the global `status` can be explained by the presence in the cluster of peers in 0.13.0 which prevent the latest state from being correctly broadcasted to everyone.
