### ISSUE TITLE
Make the necessary changes to allow running ipfs-cluster tests in kubernetes-ipfs real cluster

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#244]
In a easy way, which can be automated and triggered remotely, obtaining the results. It should still be possible to run on minikube.

**Comment by hsanjuan** [comment]
Make the necessary changes to allow running ipfs tests (also part of kubernetes-ipfs) too.

**Comment by FrankPetrilli** [comment]
The ipfs-cluster and ipfs tests run on the real cluster, but fail on some particular tests, even with increased timeouts. I'd like some time with either you @hsanjuan or @ZenGround0 to go over the tests and why they may be failing due to not knowing the internals of ipfs-cluster.

Making this automatable and remote-triggerable will be an easy enough task - I envision an HTTP POST with a parameter indicating where to send the results on completion, which could be complete by the end of December. Do either you or @ZenGround0 forsee any issue with this implementation?

**Comment by hsanjuan** [comment]
There were some bugs fixed in ipfs, can you test again? Can you isolate the failure a little bit?

**Comment by FrankPetrilli** [comment]
Okay, just did a from-scratch redeploy. The issue is stemming from the pods who are on a different node 
than the bootstrapper. They have full network connectivity in full mesh, so this doesn't seem to be an issue.

```
## Running test 'Pin something in cluster'
## Using 2 nodes for this test
### Running step add random stuff to ipfs on nodes [1]
$ head -c 100 /dev/urandom | base64 | ipfs add -q
Running parallel on 1 nodes on iteration 0.
### Saving output from line 0 to variable HASH: QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC
### Running step add to ipfs cluster on nodes [1]
$ ipfs-cluster-ctl pin add $HASH && sleep 2
Running parallel on 1 nodes on iteration 0.
### Running step check that everyone has the pin on nodes [1 2]
$ ipfs-cluster-ctl --enc json status $HASH | jq -r '.peer_map | .[].status' | sort | uniq | tee /tmp/file.txt && cat /tmp/file.txt | wc -l
Running parallel on 2 nodes on iteration 0.
Assertion Passed
Assertion failed!
Actual value=pinning
Expected value=1

Assertion Passed
Assertion failed!
Actual value=pinning
Expected value=1

```

```
bash-4.4# ipfs-cluster-ctl --enc json status QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC
{
  "cid": "QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC",
  "peer_map": {
    "QmRMtW17qKkha2xzsTszQMSRMuYDSf9DkS2TCuywaN6q97": {
      "cid": "QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC",
      "peer": "QmRMtW17qKkha2xzsTszQMSRMuYDSf9DkS2TCuywaN6q97",
      "status": "pinned",
      "timestamp": "2017-12-01T20:04:56Z",
      "error": ""
    },
    "QmSJ93usCABSA8PZrnyB6qjatYFuXbTGgEJAxccSDmcZ1d": {
      "cid": "QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC",
      "peer": "QmSJ93usCABSA8PZrnyB6qjatYFuXbTGgEJAxccSDmcZ1d",
      "status": "pinned",
      "timestamp": "2017-12-01T20:04:56Z",
      "error": ""
    },
    "QmT2DjSPQVWi5Frtx4wCD7Apw93YmL2iEokyi5kyhfoEAa": {
      "cid": "QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC",
      "peer": "QmT2DjSPQVWi5Frtx4wCD7Apw93YmL2iEokyi5kyhfoEAa",
      "status": "pinning",
      "timestamp": "2017-12-01T20:04:56Z",
      "error": ""
    },
    "QmTLAnBT3XzshiMrPzowNFLGtNTrzUYkbtEg52cmy669Wh": {
      "cid": "QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC",
      "peer": "QmTLAnBT3XzshiMrPzowNFLGtNTrzUYkbtEg52cmy669Wh",
      "status": "pinned",
      "timestamp": "2017-12-01T20:04:56Z",
      "error": ""
    },
    "QmZijNTT52C7VKVfHt1kxJWyWAiYTHGPLqRUVok4xSHnvH": {
      "cid": "QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC",
      "peer": "QmZijNTT52C7VKVfHt1kxJWyWAiYTHGPLqRUVok4xSHnvH",
      "status": "pinning",
      "timestamp": "2017-12-01T20:04:56Z",
      "error": ""
    },
    "Qmb4HszqjUB1toCcwVwr6kq9NJj1GDDmU7EFJMeV43f6yV": {
      "cid": "QmSBhA5VpT9iW4ziUj5dbWvXevWoCcCqYF8dq4zJdMU3EC",
      "peer": "Qmb4HszqjUB1toCcwVwr6kq9NJj1GDDmU7EFJMeV43f6yV",
      "status": "pinned",
      "timestamp": "2017-12-01T20:04:56Z",
      "error": ""
    }
  }
}
```


```
QmRMtW17qKkha2xzsTszQMSRMuYDSf9DkS2TCuywaN6q97 | Sees 5 other peers
  > Addresses:
    - /ip4/10.244.1.169/tcp/9096/ipfs/QmRMtW17qKkha2xzsTszQMSRMuYDSf9DkS2TCuywaN6q97
    - /ip4/127.0.0.1/tcp/9096/ipfs/QmRMtW17qKkha2xzsTszQMSRMuYDSf9DkS2TCuywaN6q97
  > IPFS: QmYyv68e9LZuDdjFkAw47qh5fBWKkamR2WLteH7TfydEYJ
    - /ip4/10.244.1.169/tcp/4001/ipfs/QmYyv68e9LZuDdjFkAw47qh5fBWKkamR2WLteH7TfydEYJ
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmYyv68e9LZuDdjFkAw47qh5fBWKkamR2WLteH7TfydEYJ
    - /ip6/::1/tcp/4001/ipfs/QmYyv68e9LZuDdjFkAw47qh5fBWKkamR2WLteH7TfydEYJ
QmSJ93usCABSA8PZrnyB6qjatYFuXbTGgEJAxccSDmcZ1d | Sees 5 other peers
  > Addresses:
    - /ip4/10.244.1.166/tcp/9096/ipfs/QmSJ93usCABSA8PZrnyB6qjatYFuXbTGgEJAxccSDmcZ1d
    - /ip4/127.0.0.1/tcp/9096/ipfs/QmSJ93usCABSA8PZrnyB6qjatYFuXbTGgEJAxccSDmcZ1d
  > IPFS: QmQnVKnoVTLsmtaCUPdAqxHkqujnhc95UFVRx9HxMKhHiR
    - /ip4/10.244.1.166/tcp/4001/ipfs/QmQnVKnoVTLsmtaCUPdAqxHkqujnhc95UFVRx9HxMKhHiR
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmQnVKnoVTLsmtaCUPdAqxHkqujnhc95UFVRx9HxMKhHiR
    - /ip6/::1/tcp/4001/ipfs/QmQnVKnoVTLsmtaCUPdAqxHkqujnhc95UFVRx9HxMKhHiR
QmT2DjSPQVWi5Frtx4wCD7Apw93YmL2iEokyi5kyhfoEAa | Sees 5 other peers
  > Addresses:
    - /ip4/10.244.0.24/tcp/9096/ipfs/QmT2DjSPQVWi5Frtx4wCD7Apw93YmL2iEokyi5kyhfoEAa
    - /ip4/127.0.0.1/tcp/9096/ipfs/QmT2DjSPQVWi5Frtx4wCD7Apw93YmL2iEokyi5kyhfoEAa
  > IPFS: QmNT9PPV8Z9jZYsicejvGJdXiQiihdysQM7EGGBSuPT4yR
    - /ip4/10.244.0.24/tcp/4001/ipfs/QmNT9PPV8Z9jZYsicejvGJdXiQiihdysQM7EGGBSuPT4yR
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmNT9PPV8Z9jZYsicejvGJdXiQiihdysQM7EGGBSuPT4yR
    - /ip4/138.197.213.212/tcp/2209/ipfs/QmNT9PPV8Z9jZYsicejvGJdXiQiihdysQM7EGGBSuPT4yR
    - /ip6/::1/tcp/4001/ipfs/QmNT9PPV8Z9jZYsicejvGJdXiQiihdysQM7EGGBSuPT4yR
QmTLAnBT3XzshiMrPzowNFLGtNTrzUYkbtEg52cmy669Wh | Sees 5 other peers
  > Addresses:
    - /ip4/10.244.1.164/tcp/9096/ipfs/QmTLAnBT3XzshiMrPzowNFLGtNTrzUYkbtEg52cmy669Wh
    - /ip4/127.0.0.1/tcp/9096/ipfs/QmTLAnBT3XzshiMrPzowNFLGtNTrzUYkbtEg52cmy669Wh
  > IPFS: Qmanyy8tnnMU7jUaB3fnEJQtS5jCJdm8cLKLyZauzwpzvS
    - /ip4/10.244.1.164/tcp/4001/ipfs/Qmanyy8tnnMU7jUaB3fnEJQtS5jCJdm8cLKLyZauzwpzvS
    - /ip4/127.0.0.1/tcp/4001/ipfs/Qmanyy8tnnMU7jUaB3fnEJQtS5jCJdm8cLKLyZauzwpzvS
    - /ip6/::1/tcp/4001/ipfs/Qmanyy8tnnMU7jUaB3fnEJQtS5jCJdm8cLKLyZauzwpzvS
QmZijNTT52C7VKVfHt1kxJWyWAiYTHGPLqRUVok4xSHnvH | Sees 5 other peers
  > Addresses:
    - /ip4/10.244.0.25/tcp/9096/ipfs/QmZijNTT52C7VKVfHt1kxJWyWAiYTHGPLqRUVok4xSHnvH
    - /ip4/127.0.0.1/tcp/9096/ipfs/QmZijNTT52C7VKVfHt1kxJWyWAiYTHGPLqRUVok4xSHnvH
  > IPFS: QmQfN9vzeUj4ojdeCYErYrYKGJXeDeD9Y4QxUoAQbMUSz4
    - /ip4/10.244.0.25/tcp/4001/ipfs/QmQfN9vzeUj4ojdeCYErYrYKGJXeDeD9Y4QxUoAQbMUSz4
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmQfN9vzeUj4ojdeCYErYrYKGJXeDeD9Y4QxUoAQbMUSz4
    - /ip4/138.197.213.212/tcp/2210/ipfs/QmQfN9vzeUj4ojdeCYErYrYKGJXeDeD9Y4QxUoAQbMUSz4
    - /ip6/::1/tcp/4001/ipfs/QmQfN9vzeUj4ojdeCYErYrYKGJXeDeD9Y4QxUoAQbMUSz4
Qmb4HszqjUB1toCcwVwr6kq9NJj1GDDmU7EFJMeV43f6yV | Sees 5 other peers
  > Addresses:
    - /ip4/10.244.1.165/tcp/9096/ipfs/Qmb4HszqjUB1toCcwVwr6kq9NJj1GDDmU7EFJMeV43f6yV
    - /ip4/127.0.0.1/tcp/9096/ipfs/Qmb4HszqjUB1toCcwVwr6kq9NJj1GDDmU7EFJMeV43f6yV
  > IPFS: QmPzSi6SdVy5LZCHHF1qFvVpKX2NPS46qJG3on5NgihnZP
    - /ip4/10.244.1.165/tcp/4001/ipfs/QmPzSi6SdVy5LZCHHF1qFvVpKX2NPS46qJG3on5NgihnZP
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmPzSi6SdVy5LZCHHF1qFvVpKX2NPS46qJG3on5NgihnZP
    - /ip6/::1/tcp/4001/ipfs/QmPzSi6SdVy5LZCHHF1qFvVpKX2NPS46qJG3on5NgihnZP
```

**Comment by hsanjuan** [comment]
hmm try running with this container: hsanjuan/ipfs-cluster-test:latest

I think the default one is still using the last stable release of ipfs, therefore pinning hangs very often.

**Comment by hsanjuan** [comment]
Hey, I have tried myself and tests work for me.

You do have to run `./runner.sh` with the right values and it creates the whole thing and substitutes the right values in the tests and templates. I did `./runner.sh 5 5`, commenting the last part (the for loop that calls `kubernetes-ipfs` to run the tests, and the running them manually one by one.

Test 0008 needs a change (https://github.com/ipfs/kubernetes-ipfs/pull/38)

Test 0009 probably needs a cluster configuration adjustment (so it rebalances a bit sooner, or a longer delay). Manually checking those pins gives me a correct replication factor of 3 despite the test failing, but that's probably after unblocking, so gotta see if the rebalancing actually happens or not. Here's the error for 0009

```
root@archives-k8s:~/go/src/github.com/ipfs/kubernetes-ipfs/ipfs-cluster# kubernetes-ipfs tests/0009-replication_self_heal.yml 
## Running test 'pin with replication factor and block some nodes'
## Using 5 nodes for this test
### Running step add Y things to ipfs on nodes [1]
$ head -c 100 /dev/urandom | base64 | ipfs add -q && sleep 1
Running parallel on 1 nodes on iteration 0.
### Appending output from line 0 to array variable HASH: QmTvJ1HW9oFDKUTaaXGnXx1RFenW2UXGagKYy6FniD4qnU
### Running step add Y things to ipfs on nodes [1]
$ head -c 100 /dev/urandom | base64 | ipfs add -q && sleep 1
Running parallel on 1 nodes on iteration 1.
### Appending output from line 0 to array variable HASH: QmZhnrNurJzx3NXcYBNwMUE91KnoCv49B7TCNwCTKQJonD
### Running step add Y things to ipfs on nodes [1]
$ head -c 100 /dev/urandom | base64 | ipfs add -q && sleep 1
Running parallel on 1 nodes on iteration 2.
### Appending output from line 0 to array variable HASH: QmVK7PUWw1LgrNJ4pCpi8o9WvczPEoAsgvZGc72Gwerqo1
### Running step add Y things to ipfs on nodes [1]
$ head -c 100 /dev/urandom | base64 | ipfs add -q && sleep 1
Running parallel on 1 nodes on iteration 3.
### Appending output from line 0 to array variable HASH: QmcL4QmUxjSiRrXBY4tzGurWgFpGKm5xuxttCLTe5ghPZT
### Running step add Y things to ipfs on nodes [1]
$ head -c 100 /dev/urandom | base64 | ipfs add -q && sleep 1
Running parallel on 1 nodes on iteration 4.
### Appending output from line 0 to array variable HASH: QmQC2YfwMpiV7FWLpo3ofDauiFr46DX2xgd5B93Eanutij
### Running step pin Y things to cluster with rep factor = 3 on nodes [4]
$ ipfs-cluster-ctl pin add -r 3 ${HASH[%i]} && sleep 1
Running parallel on 1 nodes on iteration 0.
### Running step pin Y things to cluster with rep factor = 3 on nodes [2]
$ ipfs-cluster-ctl pin add -r 3 ${HASH[%i]} && sleep 1
Running parallel on 1 nodes on iteration 1.
### Running step pin Y things to cluster with rep factor = 3 on nodes [2]
$ ipfs-cluster-ctl pin add -r 3 ${HASH[%i]} && sleep 1
Running parallel on 1 nodes on iteration 2.
### Running step pin Y things to cluster with rep factor = 3 on nodes [2]
$ ipfs-cluster-ctl pin add -r 3 ${HASH[%i]} && sleep 1
Running parallel on 1 nodes on iteration 3.
### Running step pin Y things to cluster with rep factor = 3 on nodes [2]
$ ipfs-cluster-ctl pin add -r 3 ${HASH[%i]} && sleep 1
Running parallel on 1 nodes on iteration 4.
### Running step block other random nodes on nodes [4 2]
$ killall -STOP ipfs-cluster-service
Running parallel on 2 nodes on iteration 0.
### Running step wait for rebalancing to complete on nodes [1]
$ sleep 50
Running parallel on 1 nodes on iteration 0.
### Running step check that each hash is still present on 3 nodes on nodes [1]
$ ipfs-cluster-ctl --enc json status ${HASH[%i]} | jq -r '.peer_map | .[].status' > /tmp/pin-status.txt && grep 'pinned' /tmp/pin-status.txt | wc -l
Running parallel on 1 nodes on iteration 0.
Assertion Passed
### Running step check that each hash is still present on 3 nodes on nodes [5]
$ ipfs-cluster-ctl --enc json status ${HASH[%i]} | jq -r '.peer_map | .[].status' > /tmp/pin-status.txt && grep 'pinned' /tmp/pin-status.txt | wc -l
Running parallel on 1 nodes on iteration 1.
Assertion failed!
Actual value=2
Expected value=3

### Running step check that each hash is still present on 3 nodes on nodes [1]
$ ipfs-cluster-ctl --enc json status ${HASH[%i]} | jq -r '.peer_map | .[].status' > /tmp/pin-status.txt && grep 'pinned' /tmp/pin-status.txt | wc -l
Running parallel on 1 nodes on iteration 2.
Assertion Passed
### Running step check that each hash is still present on 3 nodes on nodes [3]
$ ipfs-cluster-ctl --enc json status ${HASH[%i]} | jq -r '.peer_map | .[].status' > /tmp/pin-status.txt && grep 'pinned' /tmp/pin-status.txt | wc -l
Running parallel on 1 nodes on iteration 3.
Assertion failed!
Actual value=2
Expected value=3

### Running step check that each hash is still present on 3 nodes on nodes [3]
$ ipfs-cluster-ctl --enc json status ${HASH[%i]} | jq -r '.peer_map | .[].status' > /tmp/pin-status.txt && grep 'pinned' /tmp/pin-status.txt | wc -l
Running parallel on 1 nodes on iteration 4.
Assertion failed!
Actual value=2
Expected value=3

### Running step restore cluster service daemon on nodes [4 2]
$ killall -CONT ipfs-cluster-service
Running parallel on 2 nodes on iteration 0.
2017-12-05 12:52:07.788896314 +0000 UTC
Now waiting for 0 seconds before shutdown...
============================
== Test Summary
===============
==
== Started: 2017-12-05 12:50:07.568655184 +0000 UTC
== Ended: 2017-12-05 12:52:07.788978166 +0000 UTC
==
== Successes: 2/3 (success/failure)
== Timeouts: 0
```

**Comment by FrankPetrilli** [comment]
Hey @hsanjuan, do you have some time later today to go over some failures I'm still experiencing? I'm seeing `16:36:05.731 ERROR   apitypes: input isn't valid multihash types.go:332` and `jq` failing to parse some JSON output from a test run.

I have a working remote POST request that triggers a test run and responds with results, now I'm tweaking to get the test to run without fail.

**Comment by FrankPetrilli** [comment]
An update as we wrap up Q4 2017:


> In a easy way, which can be automated and triggered remotely, obtaining the results. It should still be possible to run on minikube.

The task is triggerable by issuing an HTTP POST to the k8s master using the code in the following file: `https://github.com/ipfs/kubernetes-ipfs/blob/346a50aa442137903c2d07fd44ca96417526531e/ipfs-cluster/trigger-server.go`.

This is:

* Automatable (HTTP POST from any language)
* Remotely triggerable (Remote HTTP POST)
* Obtainable results (The HTTP POST response is the output of running the tests)
* Able to run on minikube (Just run it on the kubernetes node)

I made the above comment a few days ago requesting @hsanjuan's assistance with diagnosing the issues the cluster is still encountering on the real cluster. You've indicated that this runs flawlessly on minikube before, but we've seen issues that are universal. I'd like to validate the source of this error so that we can progress forward. If this is to your liking @hsanjuan, can we close this issue?

**Comment by hsanjuan** [comment]
> Hey @hsanjuan, do you have some time later today to go over some failures I'm still experiencing? I'm seeing 16:36:05.731 ERROR apitypes: input isn't valid multihash types.go:332 and jq failing to parse some JSON output from a test run.

On what test is this happening, doing what request? Can you get some debug output? What's the response that jq cannot parse?

Regarding the script, I wish you had submitted it for a code review. It would need some authentication, It would also be good if it can stream the output of the tests as they happen. Then it should be integrated in cluster. This means that the cluster container that will be tested with every PR needs to be built, so the program needs to checkout the current sources (I guess github POST contains the relevant information) and do a docker build before it can run any tests. You may need to run a docker registry along it and let kubernetes use it.

We shouldn't run things manually on the cluster, thus the program would need to be packaged (with whatever method is most convienient - docker perhaps) and the deployment of it automated (the cluster's deployment should be automated too but that's a different issue). A .service file to run it at boot may be needed (although docker can run stuff on start). There's a lot more to do here....

kubernetes-ipfs could well be a program that offers this endpoint (without need of a separate thing that runs an .exec), but this would mean we move away from current scripts and propose a more standarized way of running the bootstrap of the testing clusters (a way which is hopefully application agnostic).

**Comment by FrankPetrilli** [comment]
Discussed this in the standup with @hsanjuan today:

We'll deploy it with a on-start generated shared secret, which can be retrieved from the master node.

It'll be packaged as a systemd .service file so that it runs on startup, etc.

I'll be documenting master setup, perhaps via Ansible.

I'll be getting Hector data from a failed test run to further diagnose the origin of these test failures.

**Comment by FrankPetrilli** [comment]
Okay, latest build of ipfs-cluster seems to have run successfully.

I've modified the trigger server to generate/take a secret and place the results into IPFS, then respond with that IPFS addr to the client requesting the run.

An example run that went fully successfully is here, having been remotely triggered: https://gateway.ipfs.io/ipfs/QmXRXvVSV2pYVWsstpKYtao2Jqc8qUYkJCTrHup9hsSeyo

With this, test failures are covered, it's been packaged and modified as requested. Master setup more accurately falls into #245, so @hsanjuan, does this fit what you were looking for for this issue?

**Comment by hsanjuan** [comment]
Hi, please get accustomed to making PRs with your code. It's a better way to get feedback and have others understand what exactly you have changed.

From your message it's not clear what you've modified exactly, what's been packaged and how. I guess I can go looking for a commit somewhere, but that's not a good way to do things.

**Comment by FrankPetrilli** [comment]
As Kubernetes-IPFS is primarily maintained by me and the commits to the trigger server are inside kubernetes-ipfs, I made the commits directly.

The commit you're looking for is shown directly above the message you responded to, and its commit message covers:

- What's been modified (adding shared secret, generation thereof)
- What's been packaged (the trigger-server)
- How (systemd), RPM/DEB

The commit is https://github.com/ipfs/kubernetes-ipfs/commit/fbffb603f15691797829febe83bdcfa93209e654 in case what I'm referring to is unavailable for some reason.

**Comment by ZenGround0** [comment]
@FrankPetrilli to make sure we're all on the same page Pull Request workflow is the way things work in the ipfs & friends universe.  While I understand it is a little easier for you to push straight to master and it might seem unnecessary to you right now to make a PR, from the perspective of someone reviewing your code, and the project all around, it is better for you to introduce changes in PRs.  The UI for requesting code review, discussing issues and suggesting changes, and recording the history documenting what took place (discussion, revision, insight) along with these changes help us keep our work organized and our code quality high.  

You might argue that making comments on the commit above works fine for this, but notice that you needed two comments on the issue to let Hector know that something needs review and then to link the commit.  With github's PR UI you can just request us as reviewers, we get an email, boom code review in process.

**Comment by FrankPetrilli** [comment]
Understood; I'll make that my workflow from now on.

**Comment by hsanjuan** [comment]
Please re-submit that commit as a PR @FrankPetrilli
